// Cross-platform helpers for writing generated bytes to a usable URI, sharing
// files, and saving images to the device gallery. Native uses React Native CLI
// modules; web falls back to data URIs and a synthetic <a download> click.
import { Platform } from 'react-native';
import { fromByteArray } from 'base64-js';
import CameraRoll from '@react-native-community/cameraroll';
import {
  readFileAsBase64,
  writeBase64File,
  saveFile,
  shareFiles,
} from '@/lib/phase6/Phase6FileService';
import { addPhase6History } from '@/lib/phase6/Phase6History';
import { getDefaultFolder } from '@/lib/features/settings/SettingsService';
import { manipulateAsync, SaveFormat } from '@/shims/expo-image-manipulator';
// @ts-ignore - upng-js has no types
import UPNG from 'upng-js';

function base64ToDataUri(base64: string, mime: string) {
  return `data:${mime};base64,${base64}`;
}

/** Encodes an RGBA buffer as a PNG and returns a URI usable as an <Image> source. */
export async function writePngFromRGBA(rgba: Uint8ClampedArray, width: number, height: number): Promise<string> {
  const pngBuffer: ArrayBuffer = UPNG.encode([rgba.buffer], width, height, 0);
  const base64 = fromByteArray(new Uint8Array(pngBuffer));
  return writeBase64Image(base64, 'png');
}

/** Persists a base64 payload to a file (native) or a data: URI (web) and returns the URI. */
export async function writeBase64Image(base64: string, ext: 'png' | 'jpg' | 'webp' = 'png'): Promise<string> {
  const mime = ext === 'png' ? 'image/png' : ext === 'webp' ? 'image/webp' : 'image/jpeg';
  if (Platform.OS === 'web') {
    return base64ToDataUri(base64, mime);
  }
  return writeBase64File(base64, `photo-tools-${Date.now()}-${Math.round(Math.random() * 1e6)}.${ext}`);
}

/**
 * Convert an existing image URI to WEBP format.
 * On web, uses Canvas toDataURL('image/webp') — all modern browsers support it.
 * On native, uses the React Native image-resizer adapter exposed by the
 * internal image-manipulation shim. The returned extension always matches the
 * encoded bytes.
 *
 * Returns { uri, ext } so callers can use the correct file extension.
 */
export async function convertToWebP(
  uri: string,
  quality = 0.88
): Promise<{ uri: string; ext: 'webp' | 'jpg' }> {
  if (Platform.OS === 'web') {
    const dataUrl = await new Promise<string>((resolve, reject) => {
      const img = new window.Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = img.width;
        canvas.height = img.height;
        const ctx = canvas.getContext('2d')!;
        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL('image/webp', quality));
      };
      img.onerror = () => reject(new Error('Failed to load image for WEBP conversion'));
      img.src = uri;
    });
    return { uri: dataUrl, ext: 'webp' };
  }

  if (/\.webp(?:$|\?)/i.test(uri)) return { uri, ext: 'webp' };
  const result = await manipulateAsync(uri, [], {
    compress: quality,
    format: SaveFormat.WEBP,
  });
  if (!result.uri || result.uri === uri) {
    throw new Error('Native WEBP conversion is unavailable in this build.');
  }
  return { uri: result.uri, ext: 'webp' };
}

export function guessFileName(prefix: string, ext: string): string {
  return `${prefix}-${Date.now()}.${ext}`;
}

/** Downloads (web) or shares (native) a result file to the user. */
export async function exportFile(uri: string, fileName: string): Promise<void> {
  if (Platform.OS === 'web') {
    const a = document.createElement('a');
    a.href = uri;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    await addPhase6History({
      kind: 'download', action: 'download', fileName, uri,
      mimeType: 'application/octet-stream',
    });
    return;
  }
  const saved = await saveFile(uri, fileName, await getDefaultFolder());
  await shareFiles([saved.uri], [fileName]);
  await addPhase6History({
    kind: 'share', action: 'share-and-save', fileName, uri: saved.uri,
    mimeType: 'application/octet-stream',
    metadata: { folder: saved.folder },
  });
}

/** Saves an image result to the device's photo gallery (native only, no-op on web). */
export async function saveToGallery(uri: string): Promise<boolean> {
  if (Platform.OS === 'web') return false;
  try {
    await CameraRoll.save(uri, { type: 'photo', album: 'CSC Smart Toolkit' });
    await addPhase6History({ kind: 'download', action: 'save-to-pictures', fileName: uri.split('/').pop() ?? 'image', uri, mimeType: 'image/*' });
    return true;
  } catch {
    return false;
  }
}

export async function readFileSize(uri: string): Promise<number | undefined> {
  if (Platform.OS === 'web') {
    try {
      const res = await fetch(uri);
      const blob = await res.blob();
      return blob.size;
    } catch {
      return undefined;
    }
  }
  try {
    const base64 = await readFileAsBase64(uri);
    return Math.floor(base64.length * 0.75);
  } catch {
    return undefined;
  }
}
